# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfbbfc7e3a128f20152603deeebc5654392a28c2e62847a5c832466f8d9db54937d9e51dc15abf0374756a02681436f928dd565ef69c889522d4f76f3e0c586b

test:
  secret_key_base: 0c22c94170e95ae7ec3d05045379fb6b1875bc7735e44afba84b068b36b00af60abcdbc04da0d80a041b08fcf329fa52394c08b33cbcfad0bca3ec61d2fe521b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
